/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentTransactionsRouteImport } from './routes/student.transactions'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentFlaggedRouteImport } from './routes/student.flagged'
import { Route as StudentAccountsRouteImport } from './routes/student.accounts'
import { Route as ParentTransactionsRouteImport } from './routes/parent.transactions'
import { Route as ParentSimulateRouteImport } from './routes/parent.simulate'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentFlaggedRouteImport } from './routes/parent.flagged'
import { Route as ParentChildRouteImport } from './routes/parent.child'
import { Route as ParentAccountsRouteImport } from './routes/parent.accounts'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio-inbound'
import { Route as ApiPublicPlaidWebhookRouteImport } from './routes/api/public/plaid-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentTransactionsRoute = StudentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFlaggedRoute = StudentFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAccountsRoute = StudentAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => StudentRoute,
} as any)
const ParentTransactionsRoute = ParentTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSimulateRoute = ParentSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFlaggedRoute = ParentFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildRoute = ParentChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAccountsRoute = ParentAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ParentRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio-inbound',
  path: '/api/public/twilio-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaidWebhookRoute = ApiPublicPlaidWebhookRouteImport.update({
  id: '/api/public/plaid-webhook',
  path: '/api/public/plaid-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/parent/accounts': typeof ParentAccountsRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/flagged': typeof ParentFlaggedRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/simulate': typeof ParentSimulateRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/student/accounts': typeof StudentAccountsRoute
  '/student/flagged': typeof StudentFlaggedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/parent/accounts': typeof ParentAccountsRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/flagged': typeof ParentFlaggedRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/simulate': typeof ParentSimulateRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/student/accounts': typeof StudentAccountsRoute
  '/student/flagged': typeof StudentFlaggedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/users': typeof AdminUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/parent/accounts': typeof ParentAccountsRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/flagged': typeof ParentFlaggedRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/simulate': typeof ParentSimulateRoute
  '/parent/transactions': typeof ParentTransactionsRoute
  '/student/accounts': typeof StudentAccountsRoute
  '/student/flagged': typeof StudentFlaggedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/transactions': typeof StudentTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/plaid-webhook': typeof ApiPublicPlaidWebhookRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/student'
    | '/terms'
    | '/admin/content'
    | '/admin/merchants'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/sms'
    | '/admin/users'
    | '/invite/$token'
    | '/parent/accounts'
    | '/parent/child'
    | '/parent/flagged'
    | '/parent/settings'
    | '/parent/simulate'
    | '/parent/transactions'
    | '/student/accounts'
    | '/student/flagged'
    | '/student/settings'
    | '/student/transactions'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/api/public/plaid-webhook'
    | '/api/public/twilio-inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/content'
    | '/admin/merchants'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/sms'
    | '/admin/users'
    | '/invite/$token'
    | '/parent/accounts'
    | '/parent/child'
    | '/parent/flagged'
    | '/parent/settings'
    | '/parent/simulate'
    | '/parent/transactions'
    | '/student/accounts'
    | '/student/flagged'
    | '/student/settings'
    | '/student/transactions'
    | '/admin'
    | '/parent'
    | '/student'
    | '/api/public/plaid-webhook'
    | '/api/public/twilio-inbound'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/student'
    | '/terms'
    | '/admin/content'
    | '/admin/merchants'
    | '/admin/monitoring'
    | '/admin/reports'
    | '/admin/sms'
    | '/admin/users'
    | '/invite/$token'
    | '/parent/accounts'
    | '/parent/child'
    | '/parent/flagged'
    | '/parent/settings'
    | '/parent/simulate'
    | '/parent/transactions'
    | '/student/accounts'
    | '/student/flagged'
    | '/student/settings'
    | '/student/transactions'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/api/public/plaid-webhook'
    | '/api/public/twilio-inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicPlaidWebhookRoute: typeof ApiPublicPlaidWebhookRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/transactions': {
      id: '/student/transactions'
      path: '/transactions'
      fullPath: '/student/transactions'
      preLoaderRoute: typeof StudentTransactionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/flagged': {
      id: '/student/flagged'
      path: '/flagged'
      fullPath: '/student/flagged'
      preLoaderRoute: typeof StudentFlaggedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/accounts': {
      id: '/student/accounts'
      path: '/accounts'
      fullPath: '/student/accounts'
      preLoaderRoute: typeof StudentAccountsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/transactions': {
      id: '/parent/transactions'
      path: '/transactions'
      fullPath: '/parent/transactions'
      preLoaderRoute: typeof ParentTransactionsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/simulate': {
      id: '/parent/simulate'
      path: '/simulate'
      fullPath: '/parent/simulate'
      preLoaderRoute: typeof ParentSimulateRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/flagged': {
      id: '/parent/flagged'
      path: '/flagged'
      fullPath: '/parent/flagged'
      preLoaderRoute: typeof ParentFlaggedRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/child': {
      id: '/parent/child'
      path: '/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof ParentChildRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/accounts': {
      id: '/parent/accounts'
      path: '/accounts'
      fullPath: '/parent/accounts'
      preLoaderRoute: typeof ParentAccountsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/twilio-inbound': {
      id: '/api/public/twilio-inbound'
      path: '/api/public/twilio-inbound'
      fullPath: '/api/public/twilio-inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plaid-webhook': {
      id: '/api/public/plaid-webhook'
      path: '/api/public/plaid-webhook'
      fullPath: '/api/public/plaid-webhook'
      preLoaderRoute: typeof ApiPublicPlaidWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentAccountsRoute: typeof ParentAccountsRoute
  ParentChildRoute: typeof ParentChildRoute
  ParentFlaggedRoute: typeof ParentFlaggedRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentSimulateRoute: typeof ParentSimulateRoute
  ParentTransactionsRoute: typeof ParentTransactionsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAccountsRoute: ParentAccountsRoute,
  ParentChildRoute: ParentChildRoute,
  ParentFlaggedRoute: ParentFlaggedRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentSimulateRoute: ParentSimulateRoute,
  ParentTransactionsRoute: ParentTransactionsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAccountsRoute: typeof StudentAccountsRoute
  StudentFlaggedRoute: typeof StudentFlaggedRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentTransactionsRoute: typeof StudentTransactionsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAccountsRoute: StudentAccountsRoute,
  StudentFlaggedRoute: StudentFlaggedRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentTransactionsRoute: StudentTransactionsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicPlaidWebhookRoute: ApiPublicPlaidWebhookRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
